### ISSUE TITLE
Field._get_val_from_obj() is removed in Django 2.0

### ISSUE THREAD

**Issue by muodov** [python-social-auth/social-app-django#101]
This method was deprecated for a long time, and was removed in upcoming Django 2.0:
See https://code.djangoproject.com/ticket/24716

To reproduce, checkout the latest Django 2.0 branch, and try to edit `UserSocialAuth` object from the admin interface.

social-app-django is currently using it inside `JSONField` wrapper

**Comment by GitCMDR** [comment]
I'm also being affected by this issue. You get the error: 

Request Method: GET
Request URL: http://localhost:8000/admin/social_django/usersocialauth/10/change/
Django Version: 2.0
Exception Type: AttributeError
Exception Value: 'JSONField' object has no attribute '_get_val_from_obj'
Exception Location: /Users/my_user/.virtualenvs/my_application/lib/python3.6/site-packages/social_django/fields.py in value_from_object, line 92
Python Version: 3.6.3

**Comment by muodov** [comment]
@GitCMDR the change from my PR above fixed the problem, so you can use that as a workaround

**Comment by muodov** [comment]
related to #6
