### ISSUE TITLE
Set is_staff to true when creating new user

### ISSUE THREAD

**Issue by KunalAggarwal** [python-social-auth/social-app-django#107]
Whenever the user first logs in using any oauth2 backend (in my case google). The User gets created in the User table  in django.

I need to set the is_staff to true each time a new user record gets created. How can I do that?

**Comment by omab** [comment]
Add a custom pipeline after the user creation that will set the flag for you. Docs here https://python-social-auth.readthedocs.io/en/latest/pipeline.html#extending-the-pipeline
