### ISSUE TITLE
Can't get Facebook Strict Mode to work

### ISSUE THREAD

**Issue by rzinurov** [python-social-auth/social-app-django#112]
I've got the following message in my Facebook Dev console:
<img width="922" alt="screen shot 2018-01-15 at 23 31 51" src="https://user-images.githubusercontent.com/8040747/34964197-a74599a8-fa4c-11e7-9e60-5f174c209580.png">

According to the information here https://developers.facebook.com/docs/facebook-login/security/#strict_mode strict mode is based on the exact redirect URL match. Unfortunately, I don't think social-app-django uses this approach by default, because I can see several dynamic parameters in redirect URLs when I'm signing in with `FacebookOAuth2` backend. Is anybody else experiencing the same problem?

**Comment by rzinurov** [comment]
Please ignore me. I've realized what Facebook wants right after I submitted this issue.

**Comment by perry** [comment]
@rzinurov would you mind sharing what you needed to do to get around this new requirement? Thanks!

**Comment by Simanas** [comment]
@rzinurov Up!

**Comment by rzinurov** [comment]
In Facebook dev console I needed to provide right URL in `Valid OAuth redirect URIs` of `Facebook Login` section. The URL included `client_id` parameter and `return_scopes` set to true. This allowed me to enable strict mode without changing the code. There is `Redirect URI Validator` field in the bottom of the login settings page, which was quite useful.

**Comment by ziima** [comment]
@rzinurov Could you please be more specific. Our redirect URIs generated by social auth only contains `redirect_state` parameter in the query. We haven't found a way to set up our application on facebook to pass the strict mode. Addition of the `client_id` and `return_scopes` parameters doesn't seem to help.

**Comment by drye** [comment]
@ziima same here... The redirect URI only contains `redirect_state`, `state` and `code` parameters. I have no idea how to use the `Redirect URI Validator`, to me it looks only a 100% match is valid. What are we missing @rzinurov ?

**Comment by rzinurov** [comment]
Here is a part of my settings file:
```
AUTHENTICATION_BACKENDS = (
    ...
    'social_core.backends.facebook.FacebookOAuth2',
    ...
)

SOCIAL_AUTH_FACEBOOK_KEY = '<key>'
SOCIAL_AUTH_FACEBOOK_SECRET = '<secret>'
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']
SOCIAL_AUTH_FACEBOOK_PROFILE_EXTRA_PARAMS = {
    'fields': 'id,name,email',
}
SOCIAL_AUTH_FACEBOOK_API_VERSION = '2.11'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/'
SOCIAL_AUTH_LOGIN_ERROR_URL = '/'
SOCIAL_AUTH_BACKEND_ERROR_URL = '/'
```

```
Facebook login URL: https://<website>/login/facebook/?next=/
which redirects you to https://www.facebook.com/v2.11/dialog/oauth?scope=email&state=<state>&redirect_uri=https://<website>/complete/facebook/&client_id=<client_id>&return_scopes=true
which redirects you to https://<website>/complete/facebook/?granted_scopes=email%2Cpublic_profile&denied_scopes&code=<code>&state=<state>
```

```
Valid OAuth redirect uri in Facebook app settings:
https://<website>/complete/facebook/&client_id=<client_id>&return_scopes=true

**Comment by ziima** [comment]
Looks like the biggest problem was old version of social-core (< 1.6.0). Anyway thanks @rzinurov for the redirect overview. That helped.

**Comment by drye** [comment]
@rzinurov thank you, that helped me too. I was using an old version as well, which became evident when comparing your redirect_ur scheme to mine.

**Comment by rzinurov** [comment]
@IreliaCommitsU client_id is coming from your facebook api client settings. I don't think there can be many of them.

**Comment by rzinurov** [comment]
@nortlander when you open `https://<domain>/login/facebook/?next=/` URL in the browser, it should redirect you to `https://www.facebook.com/v2.11/dialog/oauth?scope=email&state=<state>&redirect_uri=https://<domain>/complete/facebook/&client_id=<client_id>&return_scopes=true` as I wrote above. I think you are supposed to take the value of the `redirect_uri` query parameter from this URL and put it in `Valid OAuth redirect uri` input field in Facebook dev console app settings.

**Comment by Keats** [comment]
`BaseOAuth2::auth_url` It just `urlencode` the dict of params, which gets me `https://www.facebook.com/v2.11/dialog/oauth?&client_id=<client_id>&redirect_uri=https://<domain>/complete/facebook/&state=<state>&return_scopes=true`, which is obviously not a verified URL due to the state parameter. If I manually urlencode the parameters in the right order it will create the right URL.

This is on python 3.6.4, this change in python 3.6 might be relevant: https://mail.python.org/pipermail/python-dev/2016-September/146327.html

**Comment by BenEllerby** [comment]
@rzinurov if I've upgraded the library to social-auth-app-django==2.1.0 & social-auth-core==1.7.0 does that mean the URL structure for the redirect will automatically comply with strict? _I've created a test Facebook app on which I've enabled strict only and with the upgrade all seems to work OK._ Sorry for the question, but this topic has been quite confusing for me!

**Comment by merutak** [comment]
I didn't want to upgrade python-social-auth. The only change I made eventually was this:

```
diff --git a/social/backends/facebook.py b/social/backends/facebook.py
index f76b502..1f764cd 100644
--- a/social/backends/facebook.py
+++ b/social/backends/facebook.py
@@ -28,6 +28,7 @@ class FacebookOAuth2(BaseOAuth2):
         ('id', 'id'),
         ('expires', 'expires')
     ]
+    REDIRECT_STATE = False
 
     def get_user_details(self, response):
         """Return user details from Facebook account"""
```

**Comment by krina4** [comment]
@merutak can you share what did you put in redirect uri. Did you use same uri definition that is mentioned in above comments?

**Comment by merutak** [comment]
@krina4 I haven't changed the redirect URI from previous versions, i.e.
`https://mydomain/complete/facebook/`

**Comment by zxwild** [comment]
facebook wrote in the documentation
> For apps with dynamic redirect URIs, use the **state** parameter to pass back the *dynamic* information to a limited number of redirect URIs. Then add each of the limited redirect URIs to the Valid OAuth redirect URIs list.
https://developers.facebook.com/docs/facebook-login/security/#strict_mode

In `class FacebookOAuth2(BaseOAuth2)` (1.5 version) we have unset `REDIRECT_STATE` attribute, which overridden as True which cause `redirect_state` parameter in facebook complete url.

1.7 is updated and now parameter is set by default:
`REDIRECT_STATE = False`

Actually it's required to rename this attribute in settings like:
`SOCIAL_AUTH_FACEBOOK_REDIRECT_STATE_FIELD = 'state'`
