### ISSUE TITLE
PWA, Mobile Chrome no login and redirection

### ISSUE THREAD

**Issue by tyapkov** [python-social-auth/social-app-django#117]
I have a problem with login and redirection on mobile Chrome.  In the code I have a link with _next_ as it shown in documentation:

    <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">Login with Facebook</a>

It works okay for Firefox and Chrome on desktops. However on mobile phones I have different behavior. Mobile Firefox is working fine. Mobile Chrome (normal mode or PWA mode) - User cannot login and I am redirected to /accounts/login page without any errors.

social-auth-core 1.6.0
social-auth-app-django 2.1.0

The question are: how can I debug and solve it?

**Comment by omab** [comment]
Anything in the server log?

**Comment by tyapkov** [comment]
Hi omab, it is the same question you answerted on SO. It was my fault so the issue can be closed.

**Comment by omab** [comment]
Got it, thanks!
