### ISSUE TITLE
For Postgresql use JSONB field for extra_data

### ISSUE THREAD

**Issue by pythonwebcoder** [python-social-auth/social-app-django#118]
This way the data can be queried and indexed.

**Comment by omab** [comment]
That's [already implemented](https://github.com/python-social-auth/social-app-django/blob/59f8a59052d6cbffd46d364a3480c03261a04868/social_django/fields.py#L29-L32) and I just added the docs to enable it here: https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#database
