### ISSUE TITLE
Support for tokens / secrets in database

### ISSUE THREAD

**Issue by liquidscorpio** [python-social-auth/social-app-django#121]
Is it possible to store tokens in database instead of `settings.py`? By tokens,  I mean back-end specific configuration variables like:
```
// Similarly for others too
SOCIAL_AUTH_FACEBOOK_KEY
SOCIAL_AUTH_FACEBOOK_SECRET
```

I am trying to support a use case where these values are specific to each tenant in a multi-tenant environment.

**Comment by omab** [comment]
There's no built-in solution for this, the way to do it is to define your own strategy class and extend the `get_setting` method to do the db query.
