### ISSUE TITLE
if username field is different from username (e.g. email) then existing users aren't found

### ISSUE THREAD

**Issue by makslevental** [python-social-auth/social-app-django#124]
firstly this https://github.com/python-social-auth/social-app-django/blob/master/social_django/storage.py#L73 should be

`        except (IntegrityError, Exception) as exc:`

because i'm using rest_auth and i'm getting a `ValidationError` here not `IntegrityError`. secondly you have to do something like

```
kwargs = {cls.user_model().USERNAME_FIELD: kwargs[cls.user_model().USERNAME_FIELD]}
```

In order to test for collision on the right user model field

**Comment by omab** [comment]
1. Why catch a generic `Exception`? That's just bad practice, this lib has nothing to do with `ValidationError` errors, that's up to your project to follow and react to any validation constraint setup.

2. Why that custom `kwargs` when `USERNAME_FIELD` is not used in the passed arguments?

**Comment by makslevental** [comment]
on investigating answers to these question i discovered this was primarily because i was catching `IntegrityError` and reraising `ValidationError` in my user model save method. thanks. sorry.
