### ISSUE TITLE
Facebook login not working

### ISSUE THREAD

**Issue by veronicabasso** [python-social-auth/social-app-django#132]
I am using django 1.11 and followed the steps to enable Facebook login in my project. However, when I try to login I get the following error: 
_Insecure Login Blocked: You can't get an access token or log in to this app from an insecure page. Try re-loading the page as https://_
I have SSL certificate, and I can login using Google and twitter.
I would be grateful if somebody can help me with this issue.

**Comment by jackgoh** [comment]
I have the same issue after Facebook updated the "Use Strict Mode to Redirect URI". 
Here is the fix, add this to your settings : 
`SOCIAL_AUTH_REDIRECT_IS_HTTPS = True `

**Comment by slimaidarismail** [comment]
@jackgoh, I added your code and still redirecting to http  any other solution?

**Comment by alexcsd** [comment]
@pavelulyashev 
where should i put 
`proxy_set_header X-Forwarded-Proto $scheme;`

**Comment by arjun0108** [comment]
@slimaidarismail To use HTTPS in your website, add the following in your project's settings.py file:
```python
# Force https redirect
SECURE_SSL_REDIRECT = True
# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
```

**Comment by avelino** [comment]
There is in the documentation[1] the parameter that solves the "problem" (not a problem), I think it is important to have reference on the Facebook[2] backend page (can link this issue as well)

What opinion of you?

[1] https://python-social-auth-docs.readthedocs.io/en/latest/configuration/settings.html?highlight=SOCIAL_AUTH_REDIRECT_IS_HTTPS#processing-redirects-and-urlopen
[2] https://python-social-auth-docs.readthedocs.io/en/latest/backends/facebook.html

**Comment by nabeelayub** [comment]
Try django sslserver https://github.com/teddziuba/django-sslserver it might help you.

**Comment by krabeeputh** [comment]
> Try django sslserver https://github.com/teddziuba/django-sslserver it might help you.

YES, Django SSL server can solve it. I confirmed after got the same problem. But It can help for Facebook OAuth only if use JavaScript SDK still got the same problem!!
