### ISSUE TITLE
Error "Incorrect padding" when using OpenID

### ISSUE THREAD

**Issue by claudep** [python-social-auth/social-app-django#135]
Initially reported as https://github.com/python-social-auth/social-core/issues/180

On Python 3, the secret obtained from the remote server might be saved with the binary prefix "b'secret'" in the association.secret fields, which then lead later to the "Incorrect padding" exception when trying to use that secret.

Replacing `assoc.secret = base64.encodestring(association.secret)` by `assoc.secret = base64.encodestring(association.secret).decode()` in `storage.py` seems to solve the issue.

**Comment by mmack3540** [comment]
django_openid_auth appears to have this problem in store.py, line 80. Using Django 2.0, python 3.6

**Comment by atodorov** [comment]
@omab, @claudep thanks for fixing this and for the quick release, however I am still seeing the original issue. I am trying to login with a Fedora account and that results in the Incorrect padding error.

I have rebuilt my docker images and I have

```
$ pip freeze | grep social
social-auth-app-django==3.0.0
social-auth-core==2.0.0
```

Let me know how do you want to proceed with this?

**Comment by omab** [comment]
@atodorov, which Python version?

**Comment by atodorov** [comment]
3.6

**Comment by claudep** [comment]
I played a bit again today with the new code, and it works well for my use case.

**Comment by atodorov** [comment]
@claudep, @omab is there anything I can do to help debug this problem? Maybe it is the Fedora Account System that returns bogus responses but I'd like to figure out what's happening and work on a fix. 

Our application needs to integrate with FAS and we already have PSA integrated, just need to enable this backend and not fail.

**Comment by claudep** [comment]
What's your backend definition?

**Comment by atodorov** [comment]
```
AUTHENTICATION_BACKENDS = [
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.fedora.FedoraOpenId',
    'django.contrib.auth.backends.ModelBackend',
]
```

**Comment by claudep** [comment]
I just tried to login with the Fedora provider on a locally-running app (Python 3.5, social-auth-core==2.0.0, social-auth-app-django==3.1.0) and the process was successful. I'm afraid this does not help you :-/

**Comment by atodorov** [comment]
Next week we're going to update our application and I will re-enable this backend again for testing. In case it does fail what info are you looking for ?  (note: this is a production app and I don't want to leave the backend enabled for too long if it fails so I want to be prepared to collect as much data as possible.)

**Comment by claudep** [comment]
Note that I'm not a maintainer of this app, however I'd be glad to help if possible.
Provide the error traceback please.
Also note that you should be able to test the backend when running on localhost.

**Comment by atodorov** [comment]
@omab, @claudep I still get an error about Incorrect padding. Here's my stack trace:

```
Error: Incorrect padding
  File "django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "social_django/utils.py", line 49, in wrapper
    return func(request, backend, *args, **kwargs)
  File "social_django/views.py", line 23, in auth
    return do_auth(request.backend, redirect_name=REDIRECT_FIELD_NAME)
  File "social_core/actions.py", line 27, in do_auth
    return backend.start()
  File "social_core/backends/base.py", line 34, in start
    if self.uses_redirect():
  File "social_core/backends/open_id.py", line 242, in uses_redirect
    return self.openid_request().shouldSendRedirect()
  File "social_core/backends/open_id.py", line 248, in openid_request
    params))
  File "openid/consumer/consumer.py", line 359, in begin
    return self.beginWithoutDiscovery(service, anonymous)
  File "openid/consumer/consumer.py", line 382, in beginWithoutDiscovery
    auth_req = self.consumer.begin(service)
  File "openid/consumer/consumer.py", line 610, in begin
    assoc = self._getAssociation(service_endpoint)
  File "openid/consumer/consumer.py", line 1178, in _getAssociation
    assoc = self.store.getAssociation(endpoint.server_url)
  File "social_core/store.py", line 43, in getAssociation
    for assoc_id, association in self.assoc.oids(server_url, handle):
  File "social_core/storage.py", line 227, in oids
    for assoc in cls.get(**kwargs)
  File "social_core/storage.py", line 227, in <listcomp>
    for assoc in cls.get(**kwargs)
  File "social_core/storage.py", line 235, in openid_association
    return OpenIdAssociation(assoc.handle, base64.decodestring(secret),
  File "python3.6/base64.py", line 561, in decodestring
    return decodebytes(s)
  File "python3.6/base64.py", line 553, in decodebytes
    return binascii.a2b_base64(s)
```
