### ISSUE TITLE
ImportError: cannot import name Facebook2OAuth2

### ISSUE THREAD

**Issue by souravbadami** [python-social-auth/social-app-django#14]
I've upgraded to social-app-django. I'm getting this ImportError on trying to log in using any social service. Here's the traceback:

`File "/home/sourav/myapp/venv/local/lib/python2.7/site-packages/social_core/backends/utils.py", line 35, in load_backends`
`    backend = module_member(auth_backend)`
`File "/home/sourav/myapp/venv/local/lib/python2.7/site-packages/social_core/utils.py", line 59, in module_member`
`    module = import_module(mod)`
`File "/home/sourav/myapp/venv/local/lib/python2.7/site-packages/social_core/utils.py", line 53, in import_module`
`     __import__(name)`
` File "/home/sourav/myapp/venv/local/lib/python2.7/site-packages/social/backends/facebook.py", line 1, in <module>`
`    from social_core.backends.facebook import FacebookOAuth2, FacebookAppOAuth2, \
ImportError: cannot import name Facebook2OAuth2`

**Comment by alexpantyukhin** [comment]
I have installed social-auth-app-django and tried the made the same import: it works for me.  Can not reproduce issue. It seems that `Facebook2OAuth2` is absent for now https://github.com/python-social-auth/social-core/search?utf8=%E2%9C%93&q=Facebook2OAuth2

**Comment by omab** [comment]
That was fixed by https://github.com/omab/python-social-auth/commit/b3b6d83b82f3c00ab1dddc9eaf56eaf72cadb202.

**Comment by braiangama** [comment]
I just installed the social-auth-app-django package today and came in version 1.0.0 without this change

**Comment by omab** [comment]
The change is in `python-social-auth` package, not in `social-auth-app-django`.

**Comment by braiangama** [comment]
but i had installed python-social-auth yesterday and didn't came with this change.

**Comment by omab** [comment]
@braiangama, what version?

**Comment by braiangama** [comment]
0.3.3

**Comment by omab** [comment]
@braiangama, `0.3.4` is now published with the change

**Comment by braiangama** [comment]
Now it is ok! Thanks!

**Comment by souravbadami** [comment]
I'm getting this after upgrading to `0.3.4`.
`ImportError at /complete/facebook/`.
`cannot import name GoogleOpenIdConnect`.

**Comment by omab** [comment]
@souravbadami version `0.3.5` fixes that and it's in pypi.
