### ISSUE TITLE
Redirect after "Your credentials aren't allowed" AuthForbidden Exception doesn't work.

### ISSUE THREAD

**Issue by omur-dalan** [python-social-auth/social-app-django#143]
Both with DEBUG = True and DEBUG = False modes it seems SocialAuthBaseException Middleware doesn't work. It never redirect to LOGIN_ERROR_URL or SOCIAL_AUTH_LOGIN_ERROR_URL. Using latest Django and Social-App-Django to date.

**Comment by Rinzler925** [comment]
Did you find any solution for that?

**Comment by bjorntheart** [comment]
I'm getting the same error

**Comment by Rinzler925** [comment]
here's the solution I came up for that
https://stackoverflow.com/questions/51127085/social-auth-login-error-url-not-working-django-2-0-6

**Comment by edouardtheron** [comment]
I just ran into a similar usecase, and everything worked as expected for me.

Did you check that:
1. `social_django.middleware.SocialAuthExceptionMiddleware` is added to your list of MIDDLEWARE in `settings.py`?
2. You're not using any other settings that may override `social_django` default's behaviour? [Here is the list](https://python-social-auth-docs.readthedocs.io/en/latest/configuration/django.html#exceptions-middleware) of the 4 settings attributes that **have to** be set to `False` to make it work.

**Comment by Bala-ganesh** [comment]
Hey same here also, I have deployed it k8s using helm. 
I have done all the steps mentioned in [this link](https://defectdojo.github.io/django-DefectDojo/integrations/social-authentication/#google) and as mentioned in [this link](https://github.com/DefectDojo/django-DefectDojo/blob/master/helm/defectdojo/values.yaml) I have added the extra secrets and configs to django, celery beat and worker deployment files. 

after that I can see a button letting me to choose my gmail account and later it ended up saying "Your credentials aren't allowed" 

Please let me know if you have solution or any suggestions on this. Thanks!

**Comment by oyekamal** [comment]
i solve the issue my checking my Django setting. my client_id was not correct when i updated it worked.

**Comment by Bala-ganesh** [comment]
@lukaruna Nope no luck, now we switched to azure, which is working perfectly.

**Comment by mharoonkwentra** [comment]
Have the same issue here, anyone lucky enough to solve it?

**Comment by PranavaSenthil** [comment]
<html>
<body>
<h1 style="padding: 0px; margin: 0px; font-weight: normal; color: rgb(0, 0, 0); font-family: sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">AuthForbidden at /social-auth/complete/azuread-tenant-oauth2/</h1><pre class="exception_value" style="padding: 0px; margin: 10px 0px; font-size: 1.5em; white-space: pre-wrap; font-family: sans-serif; color: rgb(87, 87, 87); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Your credentials aren't allowed</pre>

Request Method: | GET
-- | --
http://localhost:8000/social-auth/complete/azuread-tenant-oauth2/?code=0.AUoAloKLa_-92EqTrYS8vzhC9QE_VwBN8TVCjXQy2BYpN8VKAAA.AgABAAIAAAAtyolDObpQQ5VtlI4uGjEPAgDs_wUA9P8RL1x2fccXV7D8rBBvE4QChTtKmt9S1ym4JwN8j7xBZpdUrI-7YTXMfxgC1WpvsHYuMsTcP-EnrmxQrHttvRqybK-zn49wasaWVeBYTtHHfq-KFDg8j7Osn87ByV_vkGa6RtuJTOgf9Rd-2aUWSsCpCg4HuoHwLVN1qGtN9obgQfaiRLPwb_IE_rf2hCV4abb5ncGsNy7SMCM-P7VwXd7jAudGnH_vYhwhz7K2YpPcUaNr64SlZKPIZa6WrXaR5kFLeMAo_YCN8zvhY6BeKqu0rEwbqsop4KNrN8YG3INIdyzskif7nRvS03cQTriXwaCZmX9xKl-4i31L4gm6XGTJCtS7ijeHvLLUxjlww8LEbHLSoh84KwBq7g7iRJ6kPnYe9NmxYGbQwakOte1PntmHdredXt40aEoNmFk0N2cc-iSCD3kKgwCMuNn-FbfqfwT6vma651axxon3nOpDNU7NGQ9J43ZuxS0IPfUPIxrck2nntO-5ev59p-6slOuvNgCMhIV-D3gEQj7iHQrU16ne02LzE0OeVuZQKGE3BcYnAYkPihETsHmmfHon9oiFgugthAbiJhC-5BiKobeWz3JouwhMi6rdS635Pr0s71zP3pgPrJi5_-zndbofNtgDQQchiThYqOR8MCh5CgJzaV8U1z-VjdNvmjn-TuyJDq_DUI_o_moGVYLP85UU&state=NAYwqPeqo3YRriZzIUINABheTZfpJSwm&session_state=1724a548-f73a-41c5-bb84-ae8f70011314
3.2.20
AuthForbidden
Your credentials aren't allowed
C:\Users\hp\Documents\djangoauthen\myenv\Lib\site-packages\social_core\utils.py, line 258, in wrapper
C:\Users\hp\Documents\djangoauthen\myenv\Scripts\python.exe
3.11.4
['C:\\Users\\hp\\Documents\\djangoauthen\\authentication',  'C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip',  'C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python311\\DLLs',  'C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python311\\Lib',  'C:\\Users\\hp\\AppData\\Local\\Programs\\Python\\Python311',  'C:\\Users\\hp\\Documents\\djangoauthen\\myenv',  'C:\\Users\\hp\\Documents\\djangoauthen\\myenv\\Lib\\site-packages']
Thu, 24 Aug 2023 16:07:44 +0000


</body>
</html>

**Comment by vikramlance** [comment]
I got the same issue, my client secret was not correct, so that solved the issue of auth, but redirection after auth failure didn't work correctly.

**Comment by shirjeelafzal** [comment]
> I got the same issue, my client secret was not correct, so that solved the issue of auth, but redirection after auth failure didn't work correctly.

@vikramlance brother what is the client_id when sending the request from frontend is it the one got by the admin panel while registering the application or got by the google console. when i reuqest from the frontend to my backend .

**Comment by vikramlance** [comment]
> > I got the same issue, my client secret was not correct, so that solved the issue of auth, but redirection after auth failure didn't work correctly.
> 
> @vikramlance brother what is the client_id when sending the request from frontend is it the one got by the admin panel while registering the application or got by the google console. when i reuqest from the frontend to my backend .

for discord I have notes here 
https://github.com/rafalp/Misago/pull/1719#issue-2064578816
let me know if that clarifies it. You can get client ID when you register for OAUTH2, in my case for discord it has instructions here https://discordjs.guide/oauth2/#setting-up-a-basic-web-server
and on this URL page, below is the screenshot showing client id. Please go through the links so that you can get the idea. 

![image](https://github.com/python-social-auth/social-app-django/assets/15951170/e0f2335a-b24b-4037-973e-879c5caa86a8)
