### ISSUE TITLE
O-Auth Facebook Login Error

### ISSUE THREAD

**Issue by arjun0108** [python-social-auth/social-app-django#152]
All o-Auths' were working fine. But after some months later, when I checked back, all other oauths were working fine except Facebook. The **_Signup with Facebook_** button wasn't working, constantly displaying this error:

>  :exclamation:  Can't load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and sub-domains of your app to the App Domains field in your app settings.

Can anyone help me with this issue?

**Comment by arjun0108** [comment]
Due to some of the recent **Facebook Developer Apps** changes, this error occurred. The problem solved, after updating to the latest versions of **_python-social-django_** and **_social-core_**, .

**Comment by zugspitze** [comment]
Hi @arjun0108, Can you please help me what I am doing wrong:

I am getting the following error when trying to login with Facebook:

```URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.```

My redirect URI is: http://127.0.0.1:8000/auth/complete/facebook

**Comment by arjun0108** [comment]
@zugspitze Firstly, upgrade the following packages to the latest version **using pip**:
```console
social-auth-app-django
social-auth-core
```
Also, your redirect URI should be this -  [https://127.0.0.1:8000/complete/facebook/](https://127.0.0.1:8000/complete/facebook/)
Comment below, if your problem is solved.

**Comment by zugspitze** [comment]
@arjun0108 I am using the following packages:
```social-auth-app-django==2.1.0
social-auth-core==1.7.0```

And I updated my Redirect URI to https://www.hiking-buddies.com/complete/facebook/

Please check `https://www.hiking-buddies.com/routes/login_user/` for more details. It's my live website.

**Comment by arjun0108** [comment]
@zugspitze seems to be working right now. I guess there are two options for redirect URL:
Sometimes it simply works as [http://127.0.0.1:8000/complete/facebook/](http://127.0.0.1:8000/complete/facebook/) (worked for me) and sometimes it works as [http://127.0.0.1:8000/oauth/complete/facebook/](http://127.0.0.1:8000/oauth/complete/facebook/).
