### ISSUE TITLE
Missing management command.

### ISSUE THREAD

**Issue by dpaskov** [python-social-auth/social-app-django#153]
After install through pip:
`pip install social-auth-app-django==2.0.0`

The management folder is missing from the library and so management command could not be used.

**Comment by rafalp** [comment]
It seems that this was fixed 4 months ago, but hasn't been released yet:

https://github.com/python-social-auth/social-app-django/commit/c1ff02128a21d9373d7421406f9bf796c8fcef44#diff-2eeaed663bd0d25b7e608891384b7298

**Comment by rafalp** [comment]
And now you can do `pip install misago-social-auth-app-django~=2.1.0` for current master
