### ISSUE TITLE
Django 2 deprecation: New signature for from_db_value()

### ISSUE THREAD

**Issue by pjdelport** [python-social-auth/social-app-django#155]
Django 2.0 raises this deprecation warning:

> django.utils.deprecation.RemovedInDjango30Warning: Remove the context parameter from JSONField.from_db_value(). Support for it will be removed in Django 3.0.

Details: https://docs.djangoproject.com/en/2.0/releases/2.0/#context-argument-of-field-from-db-value-and-expression-convert-value

**Comment by pjdelport** [comment]
Here's a fix for another library: <https://github.com/michaeljohnbarr/django-timezone-utils/pull/9/commits/4d8441447cd3f74dcdda12074304490712910400>.

**Comment by akshaybabloo** [comment]
I think you should add a PR
