### ISSUE TITLE
social_core.backends.gitlab.GitLabOAuth2 Backend not found.

### ISSUE THREAD

**Issue by Jbertan42** [python-social-auth/social-app-django#160]
Hello,

Currently trying to use my GitLab instance as Oauth provider for a django application, when i set
```
AUTHENTICATION_BACKENDS = (
    'social_core.backends.gitlab.GitLabOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'django.contrib.auth.backends.ModelBackend',
)
```
And  
```
<a href="{% url "social:begin" "google-oauth2" %}">Google+</a>
```

It seems to work but as soon as i try to replace by 
```<a href="{% url "social:begin" "gitlab-oauth2" %}">Gitlab</a> ```
django throw a `Backend not found` exception.

Can everyone explain what's wrong ?

Thanks.

**Comment by pravinsolge15** [comment]
instead of using <a href="{% url "social:begin" "gitlab-oauth2" %}">Gitlab</a> this is replace with
<a href="{% url "social:begin" "gitlab" %}">Gitlab</a>
