### ISSUE TITLE
Facebook authentication on pythonanywhere.com not working

### ISSUE THREAD

**Issue by LonelyPenguin** [python-social-auth/social-app-django#163]
Hello, so its working on localhost :),
But then i pushed my project onto pythonanywhere.com , and now it gives me this error : 
"Can't Load URL: The domain of this URL isn't included in the app's domains. To be able to load this URL, add all domains and subdomains of your app to the App Domains field in your app settings."

I've tried everything : "wetpenguin.pythonanywhere.com" "pythonanywhere.com" "www.wetpenguin.pythonanywhere.com"

Like i dont understand whats going on to be honest, cause domain is in fact included in the app's domains. ??? Please maybe someone has any idea whats going on?

Its working on localhost

P.S.
I think maybe i must somehow include full path? wetpenguin.pythonanywhere.com/auth/complete/facebook

But if i put it into app domains, it just trims it back to wetpenguin.pythonanywhere.com

**Comment by LonelyPenguin** [comment]
Okay my bad, i will leave a fix here, so anybody else who has this problem ->

go to https://developers.facebook.com/apps/{your app id}/dashboard/

click on facebook login > settings

in Valid OAuth Redirect URIs field add

yourdomain.com/auth/complete/facebook

**Comment by omeco4christ** [comment]
I tried doing this on pythonanywhere.com and it still did not work
