### ISSUE TITLE
disconnect url is not working

### ISSUE THREAD

**Issue by DaminiBansal** [python-social-auth/social-app-django#169]
whenever i tried to hit disconnect, it throws 405 error
can anyone please help me asap.

**Comment by DaminiBansal** [comment]
Any update?
Why 405(method not allowed error)
I am stuck just because of this small error , else i need to change my library

**Comment by omab** [comment]
`disconnect` is a `POST` action to avoid attacks like an `<img>` which src attribute points to the disconnect URL.

https://github.com/python-social-auth/social-app-django/blob/ce15088d2bf04a87eb60a46eb6cbb882060ab45c/social_django/views.py#L39
