### ISSUE TITLE
New method in AbstractUserSocialAuth

### ISSUE THREAD

**Issue by NBajanca** [python-social-auth/social-app-django#17]
New method suggestion for AbstractUserSocialAuth.

Objective: Get an always updated access_token easily.

Something like this:

     from social_django.utils import load_strategy
     ...
    @classmethod
    def get_access_token(cls, provider, uid):
        if (cls.extra_data['auth_time'] + cls.extra_data['expires_in']) <= int(time.time()):
            strategy = load_strategy()
            social.refresh_token(strategy)
        return self.extra_data['access_token']

I haven't tested it, nor think about exceptions, but I can do it and do fork request. Do you agree with adding this method?

**Comment by omab** [comment]
@NBajanca, yes, I would accept a PR with that change. BTW, the `UserMixin` has an [access_token_expired()](https://github.com/python-social-auth/social-core/blob/9fb7a06a0618aa88d62b980392f77b5a5f91f98f/social_core/storage.py#L94) method that can make this code simpler to implement, something like this should do the trick:

```python
def get_access_token(self, strategy):
  if self.access_token_expired():
    self.refresh_token(strategy)
  return self.access_token
```

**Comment by omab** [comment]
Closing, reopen if still relevant.

**Comment by NBajanca** [comment]
Ok, I didn't have any time yet. But when I have I'll make a PR

**Comment by omab** [comment]
@NBajanca no hurries, thanks!

**Comment by NBajanca** [comment]
@omab does this make more sense here or on ``social-core``? In ``UserMixin``, for example.

**Comment by omab** [comment]
In `social-core` for sure.
