### ISSUE TITLE
Google sign out

### ISSUE THREAD

**Issue by vipulsingh24** [python-social-auth/social-app-django#171]
On sign out from google is there a way that users also log out from my application. I need to know whether is there any pipeline or module that when user get sign out from any social auth say google he/she should also logout from my application at the same time.

**Comment by omab** [comment]
There's no option to do that with `python-social-auth`, I would recommend looking into Google JS libraries if there's anything that can tell you if there's a user logged in on Google when your page loads or every X amount of time, and trigger a logout from your app if there's no user logged in.
