### ISSUE TITLE
GitHub  The redirect_uri MUST match the registered callback URL for this application.

### ISSUE THREAD

**Issue by SumNeuron** [python-social-auth/social-app-django#174]
Hi,
I am new to this library. I have tried googling for solutions but have not yet found one.
I am following the tutorial from simple is better than complex.

I get the error  `The redirect_uri MUST match the registered callback URL for this application.`

I do not see where I can find the redirect_uri to see what the mismatch is or how to overcome.

Any assistance would be greatly appreciated.

**Comment by morenoh149** [comment]
have you tried the answers on SO? https://stackoverflow.com/search?q=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.

**Comment by SumNeuron** [comment]
@morenoh149  yes, prior to posting I tried the solutions from 

https://stackoverflow.com/questions/23360160/python-social-auth-and-github-i-have-this-error-the-redirect-uri-must-match-th

https://stackoverflow.com/questions/42483189/authentication-failed-in-github-python-social-auth

but they did not resolve the issue

**Comment by onlyphantom** [comment]
Why is this issue closed? Can't find any pull requests that reference this issue, so it seems like it's still an outstanding issue but closed with no real solution yet.

**Comment by omab** [comment]
The problem is with the configuration on the Github side, the error reported is clear, the redirect URI must match, this is referring to the Redirect URI on the Github APP configuration, it must match the domain and redirect URL on your app.

The backend documentation has a reference to that https://python-social-auth.readthedocs.io/en/latest/backends/github.html

**Comment by fsadykov** [comment]
I think this issue should open again. I am facing issues with the same problem I checked all solutions but still the same problem. 

```
Authentication failed: The redirect_uri MUST match the registered callback URL for this application.
http://dev.academy.fuchicorp.com/oauth/complete/github/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=
```

I checked my github applicaion and it's using `https`

**Comment by fsadykov** [comment]
Hello Everyone,

I finally was able to solve this problem by changing `https` to `http` from my Github app . If you are facing same problem change to `http` even your domain name is using `https`

**Comment by stfenjobs** [comment]
this url maybe help to someone  https://github.com/python-social-auth/social-app-django/issues/31#issuecomment-277444431

**Comment by QUDUSKUNLE** [comment]
Thanks @fsadykov and @tybritten. Both tricks worked.

**Comment by tiago-peres** [comment]
It can depend in the way your `urls.py` are set too... [More about it here](https://stackoverflow.com/a/75300861/5675325)
