### ISSUE TITLE
QQ The redirect_uri cann't match

### ISSUE THREAD

**Issue by xiaoge2017** [python-social-auth/social-app-django#175]
for example:
http://127.0.0.1:8000/complete/qq 
can set for redirect_uri
http://127.0.0.1:8000/complete/qq/
cann't set for redirect_uri

so
The callback address cannot be set to the root directory
![Uploading 2018-10-07_083501.jpg…]()
i get a error"redirect uri is illegal(100010)"

but weibo can be set to the root directory 

What should I do?

**Comment by sodaling** [comment]
I also encountered this problem. 
Do you have any suggestion?
@omab

**Comment by omab** [comment]
@sodaling I need more details please.

**Comment by omab** [comment]
Could you try with this setting:

```python
SOCIAL_AUTH_TRAILING_SLASH = False
```

**Comment by sodaling** [comment]
It works! 
Thanks!
@xiaoge2017 Hope it can help you too.
