### ISSUE TITLE
How to convert code to access_token

### ISSUE THREAD

**Issue by bosiakov** [python-social-auth/social-app-django#18]
Hello! I do a REST API to authenticate via social networks.

If I login via `/login/backend/` Backend-class will receive parameter `code` and make a request to `ACCESS_TOKEN_URL` to get the `access_token`. Normal behavior for the Authorization Code Flow.

But in the [FAQ](http://python-social-auth-docs.readthedocs.io/en/latest/use_cases.html#signup-by-oauth-access-token) you propose to use `request.backend.do_auth(access_token)` for the REST API. But I have no access_token! My client has only `code`! How do I convert a `code` in the `access_token` using the methods of class `request.backend`?

**Comment by omab** [comment]
You need to call the `auth_complete()` method instead, it will call the `do_auth()` method in the end. Check the method definition at https://github.com/python-social-auth/social-core/blob/4167972181054d94c5091250b6545fa2fa6840a8/social_core/backends/oauth.py#L384
