### ISSUE TITLE
PY3 TypeError: object of type 'map' has no len()

### ISSUE THREAD

**Issue by mgiraud** [python-social-auth/social-app-django#21]
Hello !

Please, can you fix Python compatibility ?

Fix for Python 3.6 :
-pip install python3-openid
-pip install git+https://github.com/tiran/defusedxml@master

Thank you

**Comment by camilonova** [comment]
@mgiraud This was already fixed in the latest release.

**Comment by omab** [comment]
This was already fixed at `1.0.1`, also now I've enabled Python 3.6 support by enforcing `defusexml >= 0.5.0rc1` which carries the proper fix.
