### ISSUE TITLE
LookupError: No installed app with label 'default' after upgrade

### ISSUE THREAD

**Issue by amirtds** [python-social-auth/social-app-django#214]
@omab @andreif @webjunkie  I did follow https://github.com/omab/python-social-auth/blob/master/MIGRATING_TO_SOCIAL.md instructions for migration and SSO is working. the only issue is when I try to go to Django admin I see the following error `LookupError: No installed app with label 'default'.` am i missing something? Thanks

**Comment by jezdez** [comment]
Please don't just mention various people here, as each will get notified by GitHub but aren't actually maintainers of this library. Thank you.

**Comment by amirtds** [comment]
Thanks, @jezdez do you know who is the right person to ask this question? or I just leave it like this
