### ISSUE TITLE
Twitch API Update

### ISSUE THREAD

**Issue by cdelafuen** [python-social-auth/social-app-django#225]
Twitch API v3 has been shutted down in September, so that flow doesn't work anymore. It raises an error like:
`requests.exceptions.HTTPError: 410 Client Error: Gone for url: https://api.twitch.tv/kraken/user/?oauth_token=fg2t36gq2dwq0lsc8e9hx8lgfju32g`

There is a workaround if you change the line 29 of the twitch.py backends file:
` params={'oauth_token': access_token}` to `params={'oauth_token': access_token, 'api_version': 5}`
([More info here](https://dev.twitch.tv/docs/v5/guides/migration/#default-api-version))

But this workaround is not official and will be deprecated soon too, they recommend to migrate to the new [Twitch API](https://dev.twitch.tv/docs/api/)

**Comment by rigaspapas** [comment]
This has been taken care of [here](https://github.com/python-social-auth/social-core/issues/386), and will be fixed in with the next release. You can try manually pinning the `social-auth-core` package version to `3.2.0`
