### ISSUE TITLE
Is there documentation for correct redirect URI's anywhere?

### ISSUE THREAD

**Issue by calebcarithers** [python-social-auth/social-app-django#227]
I have been unable to get any form of social-auth working due to correct redirect URI's (Facebook, Twitter, Instagram, LinkedIn). Is there a specific location for documentation on the correct url paths? I have attempted the following
`
https://mydomain.com/complete/twitter/
https://www.mydomain.com/complete/twitter/
https://mydomain.com/oauth/complete/facebook/
https://mydomain.com/complete/facebook/
https://mydomain.com/complete/instagram/
https://www.mydomain.com/complete/linkedin/
`
And have received the following errors:

Facebook:
URL Blocked: This redirect failed because the redirect URI is not whitelisted in the app’s Client OAuth Settings. Make sure Client and Web OAuth Login are on and add all your app domains as Valid OAuth Redirect URIs.

Instagram:
{"error_type": "OAuthException", "code": 400, "error_message": "Redirect URI does not match registered redirect URI"}

Twitter:
403 Client Error: Forbidden for url: https://api.twitter.com/oauth/request_token

LinkedIn:
Bummer, something went wrong.
The redirect_uri does not match the registered value

**Comment by calebcarithers** [comment]
Correct redirect URI is https://mydomain.com/social-auth/complete/facebook/

**Comment by stfenjobs** [comment]
this url maybe help to someone  https://github.com/python-social-auth/social-app-django/issues/31#issuecomment-277444431
