### ISSUE TITLE
No module named 'social'

### ISSUE THREAD

**Issue by zelds** [python-social-auth/social-app-django#23]
Exception Value: 	
No module named 'social'
Exception Location: /...../python3.5/site-packages/social_core/utils.py in import_module, line 53

`/python3.5/site-packages/social_django/utils.py in wrapper

                return func(request, backend, *args, **kwargs)

     `

**Comment by softcodemark** [comment]
I assume you are using a third party social auth?

**Comment by immensity** [comment]
I am encountering same issue.

Exception Type: | ModuleNotFoundError
Exception Value: | No module named 'social'

I have upgraded to latest version, still same error.

**Comment by coler-j** [comment]
I also just ran into this issue. Weird. Never seen this before and I have been using this library alot. First time with Django 2.0.5 and python 3.6.5 though. I just had `social-auth-app-django` in my requirements and also needed to add `python-social-auth` and then it works.

**Comment by diegotejadav** [comment]
@chidimo, your solution worked for me! thanks a lot! 😄 
```sh
pip install python-social-auth
```

**Comment by omab** [comment]
@coler-j, @diegotejadav: `python-social-auth` is the old and deprecated library, by doing that you are using code that's old and not maintained anymore. The import error is report is very likely caused by settings that still point to the old library instead of the new one, some options to correct this:

1. Update any backend in `AUTHENTICATION_BACKENDS` that still reads `social.backends` to be `social_core.backends`

**Comment by diegotejadav** [comment]
@omab, and what's the new library I can use? I don't want to be using old ones.
One more thing, have you some example of using OAuth 2 with Django Rest Framework, but once again... an updated source, not an deprecated one.
Thanks for your answer.

**Comment by omab** [comment]
@diegotejadav, the new library is the one you are currently posting comments on. [social-app-django](https://github.com/python-social-auth/social-app-django).

I don't have examples for DRF.

**Comment by diegotejadav** [comment]
@omab jaja!, I'm sorry, thank you so much!
