### ISSUE TITLE
Refresh token missing in google oauth

### ISSUE THREAD

**Issue by raguljr** [python-social-auth/social-app-django#236]
**Oauth returns refresh token only for the owner of the app**(i.e when I log in). For rest of the users it is not returned. the refresh token is missing in the extra_data. The **app is unpublished**. Is that the reason for this weird behaviour? How should I overcome it?

**Comment by usamamashkoor** [comment]
@raguljr did you find any solution for this?

**Comment by kehphin** [comment]
@usamamashkoor did you find out how to fix this issue?
