### ISSUE TITLE
Crashes with Django 1.11

### ISSUE THREAD

**Issue by nijel** [python-social-auth/social-app-django#24]
With Django 1.11 you get following crash:

```
  File "/home/nijel/work/weblate/django/contrib/auth/__init__.py", line 86, in authenticate
    user = backend.authenticate(*args, **credentials)
  File "/home/nijel/work/weblate/social_core/backends/base.py", line 78, in authenticate
    return self.pipeline(pipeline, *args, **kwargs)
  File "/home/nijel/work/weblate/social_core/backends/base.py", line 81, in pipeline
    out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)
  File "/home/nijel/work/weblate/social_core/backends/base.py", line 104, in run_pipeline
    out['pipeline_index'] = pipeline_index + idx
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
```

The problem is that Django now adds positional request parameter to authenticate call and social auth accepts it as pipeline, see Django code for more details how it is done: https://github.com/django/django/blob/stable/1.11.x/django/contrib/auth/__init__.py#L69

**Comment by omab** [comment]
Fixed by https://github.com/python-social-auth/social-app-django/commit/7b8d4455bee8611845b5c485a0fd12ebe50589eb

**Comment by nijel** [comment]
Are you sure the fix is complete? The `clean_authenticate_args` method does not seem to be called anywhere...

**Comment by nijel** [comment]
Anyway I've figured out why it doesn't work as expected for me with your fix - the request is no longer available to the pipeline, I've created https://github.com/python-social-auth/social-app-django/pull/27 which does fix it.

**Comment by omab** [comment]
@nijel the fix was correct, but indeed if Django used to pass the `request` as a keyword argument, it was now missing, the request was still available by doing `strategy.request`.

**Comment by nijel** [comment]
What was more tricky is that the parameter was not missing, but it was empty dict instead, what make it a bit more tricky to discover. Using `strategy.request` seems to be better approach in this case, thanks for suggestion.

**Comment by nijel** [comment]
Any plans to release social-app-django with this fix?

**Comment by omab** [comment]
@nijel, [social-core 1.2.0](https://github.com/python-social-auth/social-core/tree/1.2.0) and [social-app-django 1.1.0](https://github.com/python-social-auth/social-app-django/tree/1.1.0) released

**Comment by nijel** [comment]
Thanks!

**Comment by naveen241192** [comment]
Can some some help me with this issue?
i am getting this same error for both google and twitter authentication.


TypeError at /social-auth/complete/facebook/
unsupported operand type(s) for +: 'NoneType' and 'int'
Request Method:	GET
Request URL:	http://mysite.com:8000/social-auth/complete/facebook/?redirect_state=TAQXEiEM8ybAubXtpIaNWj2OVNkGvOIH&code=AQDcFXPfxoGsMQwOVeZqHH3tCIEYKRw1ZMIwSdpY-NtONZJ6bklg_olWmQU1F2LlPjlF45VZBY2V1BtHdHAs0RKcCAtpzZ3hxmjTv-ckcv1Yg5CgxRqGDK6DK9q5I0uB9RBFUUhWZOU0RqXB7iYf-PhsK5H_-WzFcbYCmZ8v41EWKmcpQkx82Ro90kmAWwIkGT8c9Ky8DLiFVTwsFfZk4k-nomd4L_L9j3b_0dXvnGYzEIouqWZFqrGEdGaXL3BC2bmRHaTBLwsDp1FWo6WxAGW9nlQWDeXXdS_uBEwTj9f-4vjKK6TFAwJlsPLLBm6EPyQ8uiNGni1tD50cvYIL9FoWSzblKfUYOehrR-0ZmYGXuw&state=TAQXEiEM8ybAubXtpIaNWj2OVNkGvOIH
Django Version:	1.11.2
Exception Type:	TypeError
Exception Value:	
unsupported operand type(s) for +: 'NoneType' and 'int'
Exception Location:	C:\Python34\lib\site-packages\social\backends\base.py in run_pipeline, line 110
Python Executable:	C:\Python34\python.exe
Python Version:	3.4.3
Python Path:	
['C:\\Users\\bvsr\\PycharmProjects\\bookmarks',
 'C:\\Users\\bvsr\\PycharmProjects\\bookmarks',
 'C:\\WINDOWS\\SYSTEM32\\python34.zip',
 'C:\\Python34\\DLLs',
 'C:\\Python34\\lib',
 'C:\\Python34',
 'C:\\Python34\\lib\\site-packages']
Server time:	Tue, 27 Jun 2017 23:33:49 +0000


![image](https://user-images.githubusercontent.com/22286945/27614428-519c9314-5b67-11e7-8c5a-fee974dc1544.png)

**Comment by omab** [comment]
@naveen241192 don't hijack isssues please.

**Comment by luok4n** [comment]
@naveen241192 @omab 
i have the same problem.
can you resolved it?
thanks

**Comment by omab** [comment]
Open a new issue, @naveen241192 comment wasn't related to the original ticket, so it was never answered.
