### ISSUE TITLE
Auth Canceled at oauth/complete/Facebook when logging into facebook

### ISSUE THREAD

**Issue by Iamsoto** [python-social-auth/social-app-django#240]
![image](https://user-images.githubusercontent.com/13967954/75418427-45819a80-58e8-11ea-8634-d37c5c4a5251.png)

Keep getting this error When trying to log into facebook

My settings: 
```
SOCIAL_AUTH_FACEBOOK_KEY = os.environ.get('SOCIAL_AUTH_FACEBOOK_KEY', None) 
SOCIAL_AUTH_FACEBOOK_SECRET = os.environ.get('SOCIAL_AUTH_FACEBOOK_SECRET', None)  
SOCIAL_AUTH_FACEBOOK_SCOPE = ['email']

LOGOUT_URL = 'custom_logout'
LOGIN_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = '/'

'context_processors': [
...
                'social_django.context_processors.backends',  
                'social_django.context_processors.login_redirect', 
            ],

AUTHENTICATION_BACKENDS = (
...
    'social_core.backends.facebook.FacebookOAuth2',
```
Urls:

```
    path('oauth/', include('social_django.urls', namespace='social')), 
```

Template:
` <a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">`

On my facebook dev settings my valid callback uri is listed as 
https://myapp.com/oauth/complete/facebook

I'm using 
**social-auth-app-django==3.1.0
social-auth-core==3.2.0
python ==3.6.9
django ==3.0.2**

I'm still new at making contributions so I apologies if I'm not doing something right

**Comment by Iamsoto** [comment]
Also, 
The error above was in response to another error.
The first error: 

` http_error_msg | ('400 Client Error: Bad Request for url: '  'https://graph.facebook.com/v3.2/oauth/access_token?client_id=...&redirect_uri=...%2F&client_secret=...&code=AQC26sCIxXzfmoEUbM6Ih4yoqAj2pTuaaveUEUJs7_lhhkV8gSi5ERLIPhL-PYDnuE8eXamAtZ_Zub21UjkldS7hRUsG0m_iDH8a2Ejon3uHtVxgLox9VszDBigSSA42sEfnQ8YEVFYUfIGimvSHIK40S1yd9GxAaMC9rgdRiZzqlE_qHpMD9yYwvu1IOpmrvo6Kr3AoRzc6u6zzrZChyywoXkJeXStb5KyKlcr5M2iCzEt1AqnS7hArhiUCoBpZkjQL5yxGTeqODu-yG52tF83Ag54u8TnrINLbhgBHe5N_qUdvwgnPkA0pNenhIgL0DuArllmbJ7DJjNwrsKKuwStn')`



Maybe a repeat of #39  
Not sure just

**Comment by Iamsoto** [comment]
My problem actually ended up being an incorrect secret code 
Fun stuff!

**Comment by Iamsoto** [comment]
To anyone who has the same issue.
Hopefully the following info will help you debug: 

1) apps in Facebook's developer mode can only run on localhost 
2) apps in Facebook's live mode need a SSL certificate and the valid callback URL set

**Comment by Goury** [comment]
No, it's no help
