### ISSUE TITLE
New GitHub Release?

### ISSUE THREAD

**Issue by nileshpatra** [python-social-auth/social-app-django#244]
Hi,
The last upstream release was on Oct 31, 2018. Since there have been bug fixes, and code changes meanwhile, and it's been ~1.5 years, it would be good to have a new upstream release.
I needed this library in a project, and it would make things a lot easier for me if there's a new release.

**Comment by nileshpatra** [comment]
@omab Could you please do the needful? :)

**Comment by richardARPANET** [comment]
+1 This is much needed

**Comment by chris-bsnake** [comment]
There is a pull request that could potentially fix it: https://github.com/python-social-auth/social-app-django/pull/243

It just needs to get merged in and a new release triggered

**Comment by yurkobb** [comment]
This should be closed now as there are three new releases.
