### ISSUE TITLE
Google oauth - approval_prompt: "auto" not a valid parameter value

### ISSUE THREAD

**Issue by koressak** [python-social-auth/social-app-django#248]
Hello, 
 I have just came across an error (bug perhaps), that in my Django application, usage of the Google social auth login produces and error:

```
Error 400: invalid_request
Invalid parameter value for approval_prompt: 'auto' is not valid
```

My usage of the social auth is creating a link in a template:

`{% url 'social:begin' 'google-oauth2' %}`

No additional special configuration options, nothing. 
I suppose that this was due to some Google side change, because yesterday evening, everything worked fine.

**Comment by koressak** [comment]
Reopening this issue as I closed id upon false confirmation that it works.

**Comment by hugovk** [comment]
Yes, looks like a change on the Google side, this is affecting many sites and auth libraries.

* https://github.com/thephpleague/oauth2-client/issues/831
* https://github.com/thephpleague/oauth2-google/issues/87
* https://github.com/MarkEdmondson1234/googleAuthR/issues/177
* https://github.com/hwi/HWIOAuthBundle/issues/1622

Fix is to remove the `approval_prompt=auto` parameter or replace it with `prompt=`

https://developers.google.com/identity/protocols/oauth2/openid-connect#authenticationuriparameters

**Comment by koressak** [comment]
Thanks a lot. Closing the issue.
