### ISSUE TITLE
Is this still being maintained and updated?

### ISSUE THREAD

**Issue by selected-pixel-jameson** [python-social-auth/social-app-django#249]
Is this library still being maintained?

**Comment by sanderbrauwers** [comment]
@omab ?

**Comment by mbaechtold** [comment]
Excuse me for chiming in. The latest release of this package just happened a few hours ago (see https://github.com/python-social-auth/social-app-django/releases). So it seems to me that this package is still maintained.

What makes you think it is not the case? I know, you did not state it that bluntly, but your question must be aiming at something 🤔

**Comment by selected-pixel-jameson** [comment]
When I posted this question the repo had last been updated October of 2018.

**Comment by selected-pixel-jameson** [comment]
Closing this request as the repo seems to be receiving regular updates of some kind now.
