### ISSUE TITLE
New release 5.x on PyPI

### ISSUE THREAD

**Issue by browniebroke** [python-social-auth/social-app-django#303]
More of a question than an issue... Some Django deprecations warning have been fixed in master, but they are, to this date, [still unreleased](https://github.com/python-social-auth/social-app-django/compare/4.0.0...master).

I'm trying to fix Django deprecation warning in a project using this library and I'm trying to turn them as error when running tests, to avoid any regressions, and this app is one of the blocker.

Don't want to put pressure on the maintainer, it's not a critical problem after all, but I like to kindly ask whether a release is planned in a medium term? Are there any blocker preventing this from happening? Can I do anything to help make it happen? Sounds like it there is at least a breaking change with dropping of Python 2 support, so it should probably be v5?

Thanks for the great lib!

**Comment by bellini666** [comment]
@omab you are the one who made the latest release commit. Is that you who can release a new version of this lib? Or is there anyone else who can help us here?

**Comment by GergelyKalmar** [comment]
@nijel might be able to help as he has taken over much of the maintenance related to `social-core`.

**Comment by nijel** [comment]
I do not have access to PyPI to do the release, this is currently up to @omab.

**Comment by omab** [comment]
Release just went out https://pypi.org/project/social-auth-app-django/

@nijel, releases are automated with a Github Action, it's not documented on this project yet, but you can follow points from https://github.com/python-social-auth/social-core/wiki/Release-process
