### ISSUE TITLE
Potential Security Issue

### ISSUE THREAD

**Issue by JamieSlome** [python-social-auth/social-app-django#319]
Hello,

We recently received a vulnerability disclosure against your repository. I couldn't find an e-mail to contact or a security process to follow, so created this issue instead.

If you would like me to e-mail over the details or put them on the GitHub Issue, I'm more than happy to facilitate this for you. Otherwise, you can access the advisory [here](https://huntr.dev/bounties/1-other-python-social-auth/social-app-django/).

It is private to you and the discloser of the report.

If you have any questions, let me know.

-- Jamie from huntr.dev

**Comment by nijel** [comment]
Having test settings for Django is not a vulnerability:

https://github.com/python-social-auth/social-app-django/blob/b6e791adf96c3f13c3e499669e50093f8dc23461/tests/settings.py#L58
