### ISSUE TITLE
Release the package with Django 3.2 support

### ISSUE THREAD

**Issue by Jawayria** [python-social-auth/social-app-django#324]
We are working on upgrading edX codebase to Django 3.2. As this package is being used in the codebase, kindly consider releasing it with Django 3.2 support.

**Comment by janneronkko** [comment]
I'm already using this with Django 3.2 and things do work.

However, you do get couple of warnings that were fixed in https://github.com/python-social-auth/social-app-django/pull/314 and thus I would also like to see those commits included in a released version.

**Comment by omab** [comment]
Release with this work just went out pypi.org/project/social-auth-app-django
