### ISSUE TITLE
KeyError: 'partial_pipeline'

### ISSUE THREAD

**Issue by felipe3dfx** [python-social-auth/social-app-django#33]
Hi, i've updated form python social auth to social app Django, but i have a problem with custom partial pipeline when it redirecting to complete url:

```
backend = self.request.session['partial_pipeline']['backend']
return redirect(reverse('social:complete', args=[backend]))
```
this raises: `KeyError: 'partial_pipeline'`

how i solve this?

**Comment by omab** [comment]
The partial pipeline data is now stored in the database to allow reuse between browsers, basically we store the same data we used to store in the session, but in a db table now, then we generate a token that can be stored in the session or just appended to any URL using the `partial_token` parameter name (can be overridden by `SOCIAL_AUTH_PARTIAL_PIPELINE_TOKEN_NAME` setting).

The pipeline functions will get a `current_partial` instance which has a `token` attribute, also has a `backend` attribute with the current backend name, which can also be accessed through the `backend` parameter.

Check the [require_email](https://github.com/python-social-auth/social-examples/blob/15f87ff0a22788ccb19c946407c2ea3539ecf259/example-common/pipeline.py#L5) example.

**Comment by ip2176** [comment]
Hello, @omab if you could, I am discovering that I am hitting this error also.  This example explains how to get the backend if I am in a partial pipleline function, however, I need to access the backend in a view:

def donor_collect_details(request):
    if request.method == 'POST':
        request.session['password'] = request.POST.get('password')
        request.session['username'] = request.POST.get('username')
        request.session['first_name'] = request.POST.get('first_name')
        request.session['last_name'] = request.POST.get('last_name')
        request.session['email'] = request.POST.get('email')
        backend = request.session['partial_pipeline']['backend']
        return redirect('social:complete', backend=backend)
    return render(request, 'user/donor_collect_details.html', {'form': DonorRegistrationForm()})

We want to collect the username and information manually even when the user uses a facebook or google login, so I am trying to insert this partial into the pipeline, and I just don't know how to get the backend in a regular views.py file.  Thanks!

**Comment by omab** [comment]
@ip2176, you can get the current partial by doing:

```python
from social_core.pipeline.utils import partial_load
from social_django.utils import load_strategy

strategy = load_strategy(request)
partial = partial_load(strategy, token)
```

**Comment by tisdall** [comment]
@omab - it'd be nice if this was in the docs somewhere...  It'd also be good if there was a method that retrieved the token for you since it may be in `request.GET` or in `request.SESSION`.  I used the following to get the token (but I don't like that I had to hard code the default get arg name of `partial_token`):
```
token = request.GET.get(getattr(settings, 'SOCIAL_AUTH_PARTIAL_PIPELINE_TOKEN_NAME', 'partial_token')) or request.session.get('partial_pipeline_token')
```
