### ISSUE TITLE
Exception on gmail login

### ISSUE THREAD

**Issue by PabloLefort** [python-social-auth/social-app-django#34]
Hi! I'm having the following exception when trying to login with gmail:
```
File "project/lib/python3.5/site-packages/social_django/fields.py" line 51 in to_python
ValidationError: ['Expecting property name enclosed in double quotes: line 1 column 2 (char 1)']
```
The value of the json response is `'{\\"token_type\\": \\"Bearer\\", \\"access_toke...WVwbchW-i4gwE5-93rItgus\\", \\"expires\\": 3599}'`

Thanks in advance!

**Comment by omab** [comment]
Python version? Django version?

**Comment by PabloLefort** [comment]
@omab The versions are:
`Python 3.5.2`
`Django==1.10`

Thanks!

**Comment by levanlau** [comment]
``

>

**Comment by PabloLefort** [comment]
@omab The issue was from a migration of database. Before it was using an old version of this library.
So, udpating the db replacing '\' inside extra_data field fixed the issue.

Thanks
