### ISSUE TITLE
RemovedInDjango20Warning - on_delete

### ISSUE THREAD

**Issue by marc-gist** [python-social-auth/social-app-django#37]
Need to explicitly state the method of dealing with on_delete of related fields.

Thanks!

**Comment by omab** [comment]
This library doesn't support Django 2.0 yet.

**Comment by marc-gist** [comment]
I understand that; just thought it would be good to track and can add this without breaking current compatibility level.

**Comment by omab** [comment]
@marc-gist fair enough, I'e reopened https://github.com/python-social-auth/social-app-django/issues/6 to collect all the issues that break this integration so far.
