### ISSUE TITLE
Difficulty getting this to work with python 3.5 and django 1.10

### ISSUE THREAD

**Issue by pe82** [python-social-auth/social-app-django#38]
It worked fine on python 2.7 and django 1.9 but with python 3.5 and django 1.10, it seems that django doesn't authenticate?
even though fb returns username and the username is added to list of users, request.user still shows AnonymousUser.

**Comment by adamn** [comment]
It worked fine for me on 3.5 and 1.10 and now 3.6 and 1.11.  Does it work for you now?

**Comment by gersona** [comment]
Django version no longer supported
