### ISSUE TITLE
PKCE Support

### ISSUE THREAD

**Issue by chandrasc** [python-social-auth/social-app-django#392]
Does anyone know if PCKE is supported in upcoming updates?

**Comment by goodnewsj62** [comment]
Is code PKCE is a client only flow. eg: SPA(React) or mobile app where it's literally not possible to totally hide the client_secret. You should probably look for a frontend library if you want something of that sort.

**Comment by nijel** [comment]
It is already present: https://github.com/python-social-auth/social-core/blob/9d3ba91a632e4bf031842558aedaa5a7cf64ae7d/social_core/backends/oauth.py#L467-L529
