### ISSUE TITLE
/oauth/complete/twitter/ Missing needed parameter state

### ISSUE THREAD

**Issue by ValeriyG** [python-social-auth/social-app-django#42]
social-auth-app-django==1.1.0
social-auth-core==1.2.0
Django==1.9.7
Python 3.5

AuthMissingParameter at /oauth/complete/twitter/

**Comment by nimrand** [comment]
I'm getting the same kinds of errors with twitter as well, but only for some users, it seems.  I don't know why.

**Comment by gersona** [comment]
This Django version is no longer supported
