### ISSUE TITLE
Github Authentication Documentation

### ISSUE THREAD

**Issue by leportella** [python-social-auth/social-app-django#44]
I was very troubled on doing the github authentication implementation with `social-app-django` though the documentation.

I think it would be best to have more detailed step-by-step guidelines. One useful article I run into was this https://simpleisbetterthancomplex.com/tutorial/2016/10/24/how-to-add-social-login-to-django.html#comment-3233186393 and I would like to add a detailed guideline on the documentation.

**Comment by omab** [comment]
I've merged https://github.com/python-social-auth/social-docs/pull/11, I'll close this issue now, reopen if still relevant.

Thanks!
