### ISSUE TITLE
Missing migrations on 5.2.0?

### ISSUE THREAD

**Issue by John2013** [python-social-auth/social-app-django#448]
Seems that migrations needed for v5.2.0, but not added.

```python manage.py makemigrations --dry-run --check```
printed:
```
Migrations for 'social_django':
  .venv/lib/python3.8/site-packages/social_django/migrations/0013_auto_20230412_0755.py
    - Alter field id on association
    - Alter field id on code
    - Alter field id on nonce
    - Alter field id on partial
    - Alter field id on usersocialauth
```

Django==3.2.18

**Comment by nijel** [comment]
Maybe you already did some migration yourself (because of https://github.com/python-social-auth/social-app-django/issues/429)? There is no 0012 migration in social_django, see https://github.com/python-social-auth/social-app-django/tree/master/social_django/migrations

**Comment by John2013** [comment]
You're right, it was our migration.
