### ISSUE TITLE
Django 4.2.2 breaks the way JSONField behaves

### ISSUE THREAD

**Issue by ShaheedHaque** [python-social-auth/social-app-django#464]
### Expected behaviour

When using social-app-django's  `extra_data`, prior to Django 4.2.2, the extra data was saved as a dict. 

### Actual behaviour

With 4.2.2 it is saved as a string instead. 

### What are the steps to reproduce this issue?

Perform a normal login using a backend that uses extra data, such as SAML.

### Any logs, error output, etc?

With Django 4.2.2, and a stack that look like this:

![stack](https://github.com/python-social-auth/social-app-django/assets/4881193/451ffbdf-8647-4910-92e3-f274fcded0cd)

the code at https://github.com/python-social-auth/social-app-django/blob/8d0a2052d1b22a899454571c62237d23aa25af97/social_django/storage.py#L24 ends up behaving as follows:

1.  On entry to the two new lines of code added in Django, `value` is a dict, but is flattened into a string by the new code.
2. The call to `save()` then ends up saving a string instead of the dict.

See also the bug I originally filed against Django for this at https://code.djangoproject.com/ticket/34644.

### Any other comments?

The referenced Django bug contains suggestions from the Django team on what changes might be needed in social-app-django.

**Comment by nijel** [comment]
https://github.com/python-social-auth/social-app-django/pull/465 should address this, feedback and testing is welcome.
