### ISSUE TITLE
Drop support for Django 1.7 and below

### ISSUE THREAD

**Issue by omab** [python-social-auth/social-app-django#5]
Refs https://github.com/omab/python-social-auth/issues/909

**Comment by adamn** [comment]
A better option might be to create a new major version that drops <1.11 entirely.  You can do some minor backports to ease migration from 1.8 to 2.0 (which would require the new version of social) in the future.

**Comment by nijel** [comment]
The support for Python 2 has been dropped, so is Django 1.7.
