### ISSUE TITLE
Deprecated Sign In with LinkedIn

### ISSUE THREAD

**Issue by bernardotavares** [python-social-auth/social-app-django#504]
Sign In with LinkedIn has been deprecated since Aug 1 2023, ([deprecation notice](https://learn.microsoft.com/en-us/linkedin/consumer/integrations/self-serve/sign-in-with-linkedin)), this option is no longer available to new app developers.

This issue already describes it really well: https://github.com/supabase/gotrue/issues/1216

### Any logs, error output, etc?
**Error:**
social_core.exceptions.AuthFailed: Authentication failed: Scope &quot;r_liteprofile&quot; is not authorized for your application

**Log:**
"GET /complete/linkedin-oauth2/?error=unauthorized_scope_error&error_description=Scope+%26quot%3Br_liteprofile%26quot%3B+is+not+authorized+for+your+application&state=quZhyp3ho9wwypaJ5yR1ozIIHNYx3ywl HTTP/1.1" 500 119217
  File "C:\Python39\lib\site-packages\social_core\backends\linkedin.py", line 118, in process_error
    super().process_error(data)
  File "C:\Python39\lib\site-packages\social_core\backends\oauth.py", line 400, in process_error
    raise AuthFailed(self, data.get("error_description") or data["error"])

**Comment by rfreis** [comment]
I'm facing the same issue here

**Comment by noxan** [comment]
same here, seems like a fix was started here: https://github.com/python-social-auth/social-core/pull/829

**Comment by gersona** [comment]
- The fix is now implemented in https://github.com/python-social-auth/social-core/pull/833
- An additional PR regarding `userdetails` is still in progress https://github.com/python-social-auth/social-core/pull/915
