### ISSUE TITLE
Update to social-core 4.5.2

### ISSUE THREAD

**Issue by EveSquare** [python-social-auth/social-app-django#550]
First of all, thank you very much for maintaining and administering this library.

In January of 2023, we received an email from Meta about an API upgrade.
The content of the email was a recommendation to migrate all calls to graph APIv13.0 or later.
Details: https://developers.facebook.com/docs/graph-api/changelog

Also mentioned in `social-core`.
https://github.com/python-social-auth/social-core/pull/873

The `social-core` pull request to update to Graph APIv18.0 has been merged and released in [v4.5.2](https://github.com/python-social-auth/social-core/releases/tag/4.5.2).
Therefore, I would like to update `social-core`.

**Comment by nijel** [comment]
You can update it without raising dependency here.
