### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'provider'

### ISSUE THREAD

**Issue by i-zhivetiev** [python-social-auth/social-app-django#571]
### Expected behaviour

Users with a GitHub account should be able to log in.

### Actual behaviour

Users with a GitHub account cannot log in; instead, they receive an error.

### What are the steps to reproduce this issue?

1. Sign up with your GitHub account.
2. Log out.
3. Log in using your GitHub account.

### Any other comments?

Affected Version: 5.4.1

This happens because we are trying to compare `str` and `int` in the `AbstractUserSocialAuth.get_social_auth` method.
See https://github.com/python-social-auth/social-app-django/blob/master/social_django/models.py#L63

**Comment by nijel** [comment]
Upgrade social- auth-core, it should be addressed already there

**Comment by i-zhivetiev** [comment]
Thanks, it helps, but version 5.4.1 introduces a breaking change because `﻿social-auth-core>=4.4.1` no longer works.

**Comment by Spanish93** [comment]
Hi @i-zhivetiev can you prepare a release so all people can benefit of your fix ?
https://github.com/python-social-auth/social-core/wiki/Release-process

Thanks
