### ISSUE TITLE
Bug in social_auth.social_user pipeline stemming from AbstractUSerSocialAuth.get_social_auth

### ISSUE THREAD

**Issue by norbye** [python-social-auth/social-app-django#578]
### Context

The bug was introduced in https://github.com/python-social-auth/social-app-django/pull/566 - released in v5.4.1

It appears when the supplied user_id from an OAuth2 application is in integer-form.

### Expected behaviour

When the social_auth pipeline is run with an OAuth2 application that supplies user_id's in a numeric form, it is expected for the user_id to be compared successfully even if it is stored in string form in the database.

### Actual behaviour

As the uid in social_django/models.py/AbstractUserSocialAuth is a CharField, supplied user id's are stored as chars and returned as strings in the backend.  
In https://github.com/python-social-auth/social-app-django/pull/566, this comparison is now handled by python with a strict equals check to account for case insensitivity. With this check, user id's that are numeric are compared with their stored equivalents in string form, so it appears as if they are always new ( "1" == 1 => False).  
Thus, social_auth tries to create a new user account for each time the same user tries to log in, which fails as the database recognizes the existing row and throws an error because the unique constraint is being violated.

### What are the steps to reproduce this issue?

I got this issue on a postgreSQL database, although I imagine the value of a models.CharField would be serialized as a string value for all databases.

1. Use an authentication backend that returns user id's in numeric form
2. Try to log in with a valid account with user_id 1
3. The page crashes with the following error where <backend> is your configured backend

```
IntegrityError at /complete/<backend>/ duplicate key value violates unique constraint "social_auth_usersocialauth_provider_uid_e6b5e668_uniq"
DETAIL:  Key (provider, uid)=(<backend>, 1) already exists.
```

### Any logs, error output, etc?

I have bypassed the issue by overriding `get_user_id` as follows, but as this breaks any backend with numeric id's for v5.4.1 it would be preferable to fix it in the source code.

```python
# Within custom implementation of the social_core.backends.oauth.BaseOAuth2 class
def get_user_id(self, details, response):
        return str(super().get_user_id(details, response))
```

### Any other comments?

If you too view this as an issue that should be fixed without custom overrides like the above, I wouldn't mind submitting a PR with a fix, but I would like confirmation that this would be a useful contribution before getting started.

I'm imagining modifying https://github.com/python-social-auth/social-app-django/pull/566 to only run the case-insensitive check if the input uid is of type string would resolve the problem while still resolving the CVE.

Feel free to let me know if any part is unclear or you require more information

**Comment by norbye** [comment]
And of course I found out 10 minutes later that the bug has been resolved but not added to https://github.com/python-social-auth/social-app-django/blob/master/CHANGELOG.md or a new release, feel free to ignore this issue.

**Comment by nijel** [comment]
This has been fixed in https://github.com/python-social-auth/social-core/releases/tag/4.5.4, the social-app-django fix in https://github.com/python-social-auth/social-app-django/commit/7d8b75171ac6a67b215ac4adc7895f4a79141b01 is needed only if you use older versions of social-core.
