### ISSUE TITLE
Reauth Gitlab doesn't work

### ISSUE THREAD

**Issue by Spanish93** [python-social-auth/social-app-django#592]
Since Defect Dojo use last version of social core (5.4.1), reauth with gitlab don't work.
See : https://github.com/DefectDojo/django-DefectDojo/issues/10171

May be related with : https://github.com/python-social-auth/social-app

**Comment by nijel** [comment]
If somebody prepares the release (see https://github.com/python-social-auth/social-core/wiki/Release-process), I can publish it.
