### ISSUE TITLE
Backend for Azure Active Directory B2C

### ISSUE THREAD

**Issue by InfiniteLegend** [python-social-auth/social-app-django#61]
There's Azure service called [AD B2C](https://azure.microsoft.com/en-us/services/active-directory-b2c/https://azure.microsoft.com/en-us/services/active-directory-b2c/) for IAM. The differences between Azure AD and Azure AD B2C are different API endpoints and request/response parameters. Therefore there's a necessity to develop new backend for this service.

Functionality to be developed is common: login, sign up, logout and token refresh.

**Comment by OmarIthawi** [comment]
FYI, I'm planning to work on AD B2C backend. Will keep you posted once I have something (no promises though).

**Comment by OmarIthawi** [comment]
I suggest closing this in favor of https://github.com/python-social-auth/social-core/issues/157
