### ISSUE TITLE
BitbucketOAuth2 backend has no refresh_token method

### ISSUE THREAD

**Issue by nkprince007** [python-social-auth/social-app-django#67]
```
from django.contrib.auth.models import User

user = User.objects.all().first()
social = user.social_auth.get(provider='bitbucket-oauth2')
social.refresh_token()
```
^^ raises `NotImplementedError: Refresh tokens for Bitbucket have not been implemented`

Please provide some way to solve this problem, because bitbucket auth tokens expire really often, they have an expiry time of 1 hour. Manually refreshing the tokens is really a hard job.

**Comment by nkprince007** [comment]
Please let me know why this method was blocked, it seems to be using the correct procedure itself, right/

**Comment by omab** [comment]
Closing in favor of https://github.com/python-social-auth/social-core/issues/104
