### ISSUE TITLE
Django crash

### ISSUE THREAD

**Issue by naveen241192** [python-social-auth/social-app-django#69]
I am getting this error while doing social authentication with facebook

TypeError at /social-auth/complete/facebook/
unsupported operand type(s) for +: 'NoneType' and 'int'
Request Method:	GET
Request URL:	http://mysite.com:8000/social-auth/complete/facebook/?redirect_state=TAQXEiEM8ybAubXtpIaNWj2OVNkGvOIH&code=AQCKcmP7l_ac1XW6iOTxp3I8PtiQeVeUE7tS8hJDroWZIq4kv6G9PM5M-TQ69XPKVCSMFsAOUpYp_uuXaCONsaVhhbWwQRdcp4iJCV5Y3EbJlr53uPzx1OsQgNJz0B8Oigv1w922ME0NpAt1EEL8CXGzAPDy1bELFNOC8bmfPIGU8lh06EDp1vSg1vYy3cxC_6e1ZZp8yiyrgqTHhC9yG1WTG6WeXSQUlHrnQimF5ha6U46ZEEVwFd7sKTEZPVkhzx9ZLATIEralQvrvD1PMi0LHh3p9o2Pf3d1v9SnXI7QCmp1zsLDfOzaM_hIxbFS69ZkpY76uWCZB0GpAryXCscdMCyA62eagGY2synbdn01Puw&state=TAQXEiEM8ybAubXtpIaNWj2OVNkGvOIH
Django Version:	1.11.2
Exception Type:	TypeError
Exception Value:	
unsupported operand type(s) for +: 'NoneType' and 'int'
Exception Location:	C:\Python34\lib\site-packages\social\backends\base.py in run_pipeline, line 110
Python Executable:	C:\Python34\python.exe
Python Version:	3.4.3
Python Path:	
['C:\\Users\\bvsr\\PycharmProjects\\bookmarks',
 'C:\\Users\\bvsr\\PycharmProjects\\bookmarks',
 'C:\\WINDOWS\\SYSTEM32\\python34.zip',
 'C:\\Python34\\DLLs',
 'C:\\Python34\\lib',
 'C:\\Python34',
 'C:\\Python34\\lib\\site-packages']
Server time:	Tue, 27 Jun 2017 22:53:02 +0000
![capture](https://user-images.githubusercontent.com/22286945/27613575-e30b2e42-5b61-11e7-97bc-fa91faa78a7e.JPG)

**Comment by omab** [comment]
Post the full traceback.

**Comment by naveen241192** [comment]
Environment:


Request Method: GET
Request URL: http://mysite.com:8000/social-auth/complete/facebook/?redirect_state=TAQXEiEM8ybAubXtpIaNWj2OVNkGvOIH&code=AQCyIdFp5AT3UC6kKES2kZrK0gMcXz7_hEVYXgaO1qeuSzovUbXX3fhgNyqDHZaK9diCPp0wo911cLLelcB_fkiTROi7U3wbtPmPJDKz1PsVEUzz9X7QQjI6Z0dyGGxceTfH7y1NNs_YSbkNnyp0sIDRG5p2m3GY0b6bwCF4N1lCx6L80Eu7TCsV8Xw12vgrbpVzGJoTzmgzmmy34fjazQMpw5U8bUETFrZDxLYFv3FRt3SgRAzKfLHh1w3i5zpmWVlFXQ2RTneEfvRqhKCufr9f027HGVxIgP4QPFYTM_A57YKmp4VTytZa2oj2kp-0Tg6Za6E0qB9MMR3p6bNB8_Jb9YKXFeQfwJyJR_aZwRfVEA&state=TAQXEiEM8ybAubXtpIaNWj2OVNkGvOIH

Django Version: 1.11.2
Python Version: 3.4.3
Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'account',
 'django.contrib.admin',
 'social.apps.django_app.default']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware']



Traceback:

File "C:\Python34\lib\site-packages\django\core\handlers\exception.py" in inner
  41.             response = get_response(request)

File "C:\Python34\lib\site-packages\django\core\handlers\base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "C:\Python34\lib\site-packages\django\core\handlers\base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Python34\lib\site-packages\django\views\decorators\cache.py" in _wrapped_view_func
  57.         response = view_func(request, *args, **kwargs)

File "C:\Python34\lib\site-packages\django\views\decorators\csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "C:\Python34\lib\site-packages\social\apps\django_app\utils.py" in wrapper
  51.             return func(request, backend, *args, **kwargs)

File "C:\Python34\lib\site-packages\social\apps\django_app\views.py" in complete
  28.                        redirect_name=REDIRECT_FIELD_NAME, *args, **kwargs)

File "C:\Python34\lib\site-packages\social\actions.py" in do_complete
  44.         user = backend.complete(user=user, *args, **kwargs)

File "C:\Python34\lib\site-packages\social\backends\base.py" in complete
  41.         return self.auth_complete(*args, **kwargs)

File "C:\Python34\lib\site-packages\social\utils.py" in wrapper
  246.             return func(*args, **kwargs)

File "C:\Python34\lib\site-packages\social\backends\facebook.py" in auth_complete
  87.         return self.do_auth(access_token, response, *args, **kwargs)

File "C:\Python34\lib\site-packages\social\backends\facebook.py" in do_auth
  119.         return self.strategy.authenticate(*args, **kwargs)

File "C:\Python34\lib\site-packages\social\strategies\django_strategy.py" in authenticate
  96.         return authenticate(*args, **kwargs)

File "C:\Python34\lib\site-packages\django\contrib\auth\__init__.py" in authenticate
  69.             user = _authenticate_with_backend(backend, backend_path, request, credentials)

File "C:\Python34\lib\site-packages\django\contrib\auth\__init__.py" in _authenticate_with_backend
  114.     return backend.authenticate(*args, **credentials)

File "C:\Python34\lib\site-packages\social\backends\base.py" in authenticate
  82.         return self.pipeline(pipeline, *args, **kwargs)

File "C:\Python34\lib\site-packages\social\backends\base.py" in pipeline
  85.         out = self.run_pipeline(pipeline, pipeline_index, *args, **kwargs)

File "C:\Python34\lib\site-packages\social\backends\base.py" in run_pipeline
  110.             out['pipeline_index'] = pipeline_index + idx

Exception Type: TypeError at /social-auth/complete/facebook/
Exception Value: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by omab** [comment]
That traceback corresponds to the deprecated library https://github.com/omab/python-social-auth.

**Comment by naveen241192** [comment]
Thanks, i tried using social-auth-app-django, it is working now.
