### ISSUE TITLE
Documentation needs fixing. Partial pipeline example. AttributeError 'User' object has no attribute 'profile'

### ISSUE THREAD

**Issue by MrEmanuel** [python-social-auth/social-app-django#76]
I'm getting an error when trying to extend the pipeline following the documentation at: http://python-social-auth.readthedocs.io/en/latest/pipeline.html#extending-the-pipeline

I use Django version 1.11.4 and python 3.6
I get the error: 

```
> Exception Type: | AttributeError
> 'User' object has no attribute 'profile'
```

when trying to run the code
`profile = user.get_profile()`

After reading this:
https://stackoverflow.com/a/21734033/6862530 

I read the django documentation here:
http://django.readthedocs.io/en/latest/topics/auth/customizing.html#django.contrib.auth.models.AbstractBaseUser 

and ended up fixing the error by using using  this:
`profile = user.get_username()`

**Comment by omab** [comment]
The `profile` feature it's purely a Django feature not used by this library or the pipeline at all.
