### ISSUE TITLE
401 Client Error: Authorization Required for url: https://api.twitter.com/oauth/request_token

### ISSUE THREAD

**Issue by chenpengcheng** [python-social-auth/social-app-django#83]
Hi there,

I followed the guide on RTD and am having issues with Twitter OAuth.

Django 1.11 and 1.8 both have same issue. Any thoughts?

Thanks!

**Comment by tschwaerzl** [comment]
how did you fix it?

**Comment by chenpengcheng** [comment]
I switched to allauth package.

**Comment by volartem** [comment]
I have same error

**Comment by rahul6612** [comment]
did any one got the solution?
