### ISSUE TITLE
django.urls.exceptions.NoReverseMatch: Reverse for 'repairs-social-network-error' not found.\

### ISSUE THREAD

**Issue by pavelber** [python-social-auth/social-app-django#84]
My test application with github login worked well, but from some point of time login is not working for one of users with error

django.urls.exceptions.NoReverseMatch: Reverse for 'repairs-social-network-error' not found. 'repairs-social-network-error' is not a valid view function or pattern name

while for another user it is working

**Comment by omab** [comment]
That looks like an URL name in your project, I guess it's an incorrect configuration.
