### ISSUE TITLE
TypeError at /login/complete/facebook/

### ISSUE THREAD

**Issue by luok4n** [python-social-auth/social-app-django#85]
After to do the login with fb, when is redirecting appears this error 
Exception Type: | TypeError
-- | --
unsupported operand type(s) for +: 'NoneType' and 'int'
C:\Users\Sebastian\AppData\Local\Programs\Python\Python36-32\lib\site-packages\social\backends\base.py in run_pipeline, line 110

thanks 

![sin titulo](https://user-images.githubusercontent.com/22398463/30359685-1312fb82-9812-11e7-88ab-bde154c1651c.jpg)

**Comment by andreif** [comment]
This is fixed in master now.

**Comment by IustinTargovet** [comment]
@andreif, I still get this with the updated master

**Comment by Paul-Starodub** [comment]
i have got the same mistake now
