### ISSUE TITLE
How to handle when another account is already registered?

### ISSUE THREAD

**Issue by ravhirzldi** [python-social-auth/social-app-django#96]
Hello,
I'm facing this issue when my account is signed in using a pre-registered social media account. for example, I signed up or logged in using twitter, then I signed up again using facebook on the same email. both successfully registered.

But when I log in using the facebook account that was created earlier, then I went back to using twitter to connect both my account from my settings page, then an error message like this "AuthAlreadyAssociated at / oauth / complete / twitter"

What I'd like to ask is how to combine both my accounts and remove them when combined. or simply display an error message that the account has been registered and then go back to the previous page? thanks.

![errorrrrr](https://user-images.githubusercontent.com/33023885/32454156-f7ca5806-c350-11e7-8ba2-989ddac4146c.PNG)

**Comment by omab** [comment]
You need to extend the builtin middleware and override the needed method to take the best action that fits your app. Documentation at https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#exceptions-middleware
