### ISSUE TITLE
SocialAuthExceptionMiddleware always raises exceptions in DEBUG mode

### ISSUE THREAD

**Issue by tsouvarev** [python-social-auth/social-app-django#99]
After [commit](https://github.com/python-social-auth/social-app-django/commit/c26ae9380d01379ab794b753ce780deada71252d#diff-598f33311032accfa32e500f3c1e5783) site can't be in DEBUG mode  and not raise exceptions on social auth errors. That's very unhelpful for local development, because auth flow get interrupted with exception

**Comment by omab** [comment]
The purpose of this mode is to debug failures in the auth flow, for that exception tracebacks are essential. If desired, you can extend the middleware and override the `raise_exception` method.
